name: talha_s_application_demo
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.2.0
  intl: ^0.19.0
  camera: ^0.10.5+9
  flame: ^1.0.1
  flame_splash_screen: ^0.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  file_picker: ^6.1.1
  lottie: ^1.2.0
  google_fonts: ^6.0.0
  flutter_blue: ^0.8.0
  screen_capture_event: ^1.1.1
  external_path: ^1.0.0
  open_file: ^3.3.2
  video_player: ^2.2.13
  flutter_screen_recording: ^2.0.10
  screen_recorder: ^0.2.0
  ffmpeg_kit_flutter: ^5.1.0
  flutter_blue_plus: ^1.32.11



  web_socket_channel: ^2.2.0
  #database storage
  sqflite: ^2.3.0
  path: ^1.8.0
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2+3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  #display todos in grid
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3

#  body_detection:
#    path: lib/detection/flutter_body_detection

  google_ml_kit_example:
    path: lib/detection2/google_ml_kit_flutter/packages/example


dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inria Sans
      fonts: 
        - asset: assets/fonts/InriaSansBoldItalic.ttf
          weight: 700
        - asset: assets/fonts/InriaSansLightItalic.ttf
          weight: 300
        - asset: assets/fonts/InriaSansRegular.ttf
          weight: 400
        - asset: assets/fonts/InriaSansBold.ttf
          weight: 700
    - family: Itim
      fonts: 
        - asset: assets/fonts/ItimRegular.ttf
          weight: 400
